image: ddgg/php_2022:build_v2

pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        services:
          - mysql
          - redis
        script:
          - pushd 07_testing/02_exercise/project
          -   composer install
          -   vendor/bin/codecept build
          -   vendor/bin/php-cs-fixer fix --diff --dry-run .
          -   vendor/bin/phpstan analyze -c phpstan.neon
          -   vendor/bin/phpcpd . --fuzzy --min-lines 1 --min-tokens 20 --exclude vendor --exclude tests
          -   vendor/bin/codecept run Unit
          -   php -S localhost:8888 -t ../project/public &
          -   while ! timeout 1 bash -c "echo > /dev/tcp/localhost/6379"; do echo "Waiting for Redis..."; sleep 1; done
          -   while ! timeout 1 bash -c "echo > /dev/tcp/localhost/3306"; do echo "Waiting for MySQL..."; sleep 1; done
          -   while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8888"; do echo "Waiting for App..."; sleep 1; done
          -   vendor/bin/codecept run Acceptance
          -   vendor/bin/codecept run Acceptance --xml test_report.xml
          -   killall php
          - popd
          - .ci/collect_reports.sh
definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
    redis:
      image: redis
