image: ddgg/php_2022:build_v1

pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        script:
          - composer global require phpstan/phpstan
          - export PATH=~/.composer/vendor/bin/:$PATH
          - pushd 04_object_oriented/02_exercise/tests/
          -   phpstan analyze --level max ../project/
          -   composer install
          -   php -S localhost:8888 -t ../project/public &
          -   vendor/bin/codecept run --xml test_report.xml
          -   killall php
          - popd
          - .ci/collect_reports.sh
