image: ddgg/php_2022:build_v1

pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        services:
          - mysql
          - redis
        script:
          - composer global require friendsofphp/php-cs-fixer phpstan/phpstan sebastian/phpcpd
          - export PATH=~/.composer/vendor/bin/:$PATH
          - pushd 06_dependency_manager/02_exercise/
          -   pushd project/
          -     composer install
          -     php-cs-fixer fix --diff --dry-run .
          -     phpstan analyze --level max public/ src/
          -   popd
          -   pushd tests/
          -     composer install
          -     php -S localhost:8888 -t ../project/public &
          -     while ! timeout 1 bash -c "echo > /dev/tcp/localhost/6379"; do echo "Waiting for Redis..."; sleep 1; done
          -     while ! timeout 1 bash -c "echo > /dev/tcp/localhost/3306"; do echo "Waiting for MySQL..."; sleep 1; done
          -     vendor/bin/codecept run --xml test_report.xml
          -     killall php
          -   popd
          -   pushd project/
          -     phpcpd --fuzzy --min-lines 1 --min-tokens 10 public/ src/
          -   popd
          - popd
          - .ci/collect_reports.sh
definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
    redis:
      image: redis
